name: Run Python Scripts Hourly

on:
  schedule:
    - cron: '0 * * * *'  # This runs every hour
  workflow_dispatch:  # Allows manual runs

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Replace with the Python version you are using

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python scripts
        run: python 0.Run.py

      - name: Push changes
        run: |
          git config --global user.email "varelrod@gmail.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Update JSON outputs" -a || echo "No changes to commit"
          git push https://github-actions:${{ secrets.PAT_TOKEN }}@github.com/Poro-dev/RWA-web.git
